import struct

# Chunk Header Constants
HEADER_FORMAT = "!BQI"
HEADER_SIZE = struct.calcsize(HEADER_FORMAT)  # 13 bytes

# Nonce Constants
NONCE_PREFIX_FORMAT = "!Q"
NONCE_PREFIX_SIZE = struct.calcsize(NONCE_PREFIX_FORMAT)  # 8 bytes
NONCE_SUFFIX_SIZE = 4
NONCE_SIZE = NONCE_PREFIX_SIZE + NONCE_SUFFIX_SIZE  # 12 bytes

# AES-GCM Constants
AES_TAG_SIZE = 16

# File Constants
FILESIZE_FORMAT = "!Q"
FILESIZE_SIZE = struct.calcsize(FILESIZE_FORMAT)  # 8 bytes
MAX_FILE_SIZE = 10 * 1024 * 1024 * 1024  # 10 GB

# Flags
FLAG_COMPRESSED = 0x01
FLAG_EOF = 0x02

# Maximum Length Limits (Buffer Security)
MAX_CLIENT_ID_LEN = 1024
MAX_FILENAME_LEN = 4096
MAX_HASH_LEN = 1024
MAX_NONCE_LEN = 1024
MAX_SIG_KEY_LEN = 20000
MAX_SIG_LEN = 20000
MAX_KEM_CIPHERTEXT_LEN = 10000

# Network Settings
DEFAULT_SOCKET_TIMEOUT = 15.0
SOCKET_LINGER_TIMEOUT = 5
MAX_DRAIN_BYTES = 1024 * 1024  # 1MB
SERVER_LISTEN_BACKLOG = 10
